apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-secret-reader-writer
  namespace: default
subjects:
- kind: ServiceAccount
  name: default 
roleRef:
  kind: Role
  name: secret-reader-writer
  apiGroup: rbac.authorization.k8s.io

