apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: default
      containers:
      - image: europe-west3-docker.pkg.dev/sshsergey-main/wif-test/nginx:latest
        imagePullPolicy: Always
        name: blue
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: regcred
